/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AbstractSection: typeof import('./src/components/AbstractSection.vue')['default']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    BibTeX: typeof import('./src/components/BibTeX.vue')['default']
    FrameworkSection: typeof import('./src/components/FrameworkSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalContainer: typeof import('./src/components/ModalContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleVideo: typeof import('./src/components/SingleVideo.vue')['default']
    TextVideo: typeof import('./src/components/TextVideo.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TitleSection: typeof import('./src/components/TitleSection.vue')['default']
    VideoCarousel: typeof import('./src/components/VideoCarousel.vue')['default']
    VideoComparision: typeof import('./src/components/VideoComparision.vue')['default']
    VideoGrid: typeof import('./src/components/VideoGrid.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WrappedSection: typeof import('./src/components/WrappedSection.vue')['default']
  }
}
